### ISSUE TITLE
Not working with Django 1.7,  init() got an unexpected keyword argument 'limit_choices_to'

### ISSUE THREAD

**Issue by colinkingswood** [praekelt/django-simple-autocomplete#19]
Traceback (most recent call last):
  File "/home/colin/work/virtualenv_workspaces/virtual_env_1/lims/cnag_db/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/colin/work/virtualenv_workspaces/virtual_env_1/django-debug-toolbar/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/home/colin/work/virtualenv_workspaces/virtual_env_1/django-debug-toolbar/debug_toolbar/settings.py", line 215, in patch_all
    patch_root_urlconf()
  File "/home/colin/work/virtualenv_workspaces/virtual_env_1/django-debug-toolbar/debug_toolbar/settings.py", line 203, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 522, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 329, in app_dict
    self._populate()
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 269, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    **import**(name)
  File "/home/colin/work/virtualenv_workspaces/virtual_env_1/lims/cnag_db/urls.py", line 8, in <module>
    from sequencing import views
  File "/home/colin/work/virtualenv_workspaces/virtual_env_1/lims/cnag_db/sequencing/views.py", line 55, in <module>
    from sequencing.forms import *
  File "/home/colin/work/virtualenv_workspaces/virtual_env_1/lims/cnag_db/sequencing/forms.py", line 99, in <module>
    class SubprojectThresholdForm(ModelForm):
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/forms/models.py", line 284, in **new**
    opts.help_texts, opts.error_messages)
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/forms/models.py", line 210, in fields_for_model
    formfield = f.formfield(**kwargs)
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1769, in formfield
    return super(ForeignKey, self).formfield(**defaults)
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 339, in formfield
    return super(RelatedField, self).formfield(**defaults)
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/django/db/models/fields/**init**.py", line 842, in formfield
    return form_class(**defaults)
  File "/home/colin/work/virtualenv_workspaces/virtualenv_django_1.7/local/lib/python2.7/site-packages/simple_autocomplete/monkey.py", line 52, in ModelChoiceField__init__
    _args, *_kwargs)
TypeError: Error when calling the metaclass bases
    **init**() got an unexpected keyword argument 'limit_choices_to'

**Comment by hedleyroos** [comment]
I've released 1.9. It fixes that issue.
